### ISSUE TITLE
Problem about the function compute_VIMP

### ISSUE THREAD

**Issue by ChenXinaha** [cran/DynForest#1]
in the line 93, Inputs <- names(rf$Inputs) should be changed as "Inputs <- names(rf$Inputs[!sapply(rf$Inputs,is.null)])" because there may be Null in the elements of Inputs (Longitudinal, Numeric and Factor)

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by ChenXinaha** [comment]
Thanks
